### ISSUE TITLE
Spell Check

### ISSUE THREAD

**Issue by pvanspronsen** [perrindev/remark-web#3]
**Problem**
Users cannot seem to spell correctly.

**Solution**
A spell check feature that is capable of running at the chat input level to highlight and/or autocorrect incorrect spelling.

**Alternative Solution**
Adult English courses for any affected user.

**Additional context**
No.

**Comment by abrenoch** [comment]
IF this is as easy to get running as it looks, then this shouldn't be much trouble at all:

https://github.com/electron-userland/electron-spellchecker

devils in the details...

**Comment by abrenoch** [comment]
got a windows version of this running. As long as we can get it to compile on a mac we are in a good place.

Illiteracy prevails!
